[package]
name = "advent_of_code_rs"
version = "2019.12.2"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code-2019-rs"
license = "MIT"
description = "Solutions to Advent of Code 2019 written in Rust"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
panic = 'abort'

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "*"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "*"
